### ISSUE TITLE
Setting guidelines for repository contributors

### ISSUE THREAD

**Issue by mxochicale** [gomezalberto/pretus#33]
Hi @gomezalberto 

Wonder what's the best way to contribute to pretus? Perhaps it could be that users  either (a) create a pull request from a fork or  (b) raise an issue, create a branch and pull request. For the later, you might need to grant permissions to commit in the repo. Similarly, it would be great to see a [`CONTRIBUTING` file in the repo ](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors), where, as in the reference, you might consider to include:
```
* Steps for creating good issues or pull requests.
* Links to external documentation, mailing lists, or a code of conduct.
* Community and behavioral expectations.
```
Thanks

**Comment by gomezalberto** [comment]
Added (in docs folder)

**Comment by gomezalberto** [comment]
Based on this template:
https://gist.github.com/PurpleBooth/b24679402957c63ec426
